# Generated by Django 5.2.3 on 2025-06-18 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='mini_apps/')),
                ('app_type', models.CharField(choices=[('FR', 'Fresh App'), ('SO', 'Somosa App'), ('JR', 'Junior App'), ('SR', 'Senior App'), ('GR', 'Graduate App')], max_length=2)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
