# Generated by Django 5.2.3 on 2025-06-21 12:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0003_appreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appreview',
            name='app_variety',
        ),
        migrations.AddField(
            model_name='appreview',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='miniapp.appvariety', verbose_name='App Variety'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appreview',
            name='review_text',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='AppCertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=255)),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('issued_by', models.CharField(max_length=255)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='miniapp.appvariety', verbose_name='App Variety')),
            ],
        ),
        migrations.CreateModel(
            name='AppStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mother_company', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('app_varieties', models.ManyToManyField(related_name='stores', to='miniapp.appvariety')),
            ],
        ),
    ]
